
Debug = true
Daemon = false
[default.sandbox]
    Name = "rpc-server"
    Host = "127.0.0.1"
    Port = "8199"

[sandboxBak]
    Name = "rpc-serverv2"
    Host = "127.0.0.1"
    Port = "8921"


[sandbox.DefaultSandBox]
    Network = "tcp"
    ListenIP = "127.0.0.1"
    ListenPort = 8199
    LocalIP = "0.0.0.0"
    LocalPort = 0
    DefaultBodyCodec = "json"
    DefaultContextAge = 30
    SlowCometDuration = 30
    PrintDetail = true
    DialTimeout = 30
    RedialTimes = 1
    RedialInterval = 30

[logger]
    Path        = "/tmp/log/test-server"
    Level       = "all"
    Stdout      = true